# Generated by Django 3.2.8 on 2021-11-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsStocklist',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=50)),
                ('industry_id', models.IntegerField()),
            ],
            options={
                'db_table': 'usstocklist',
            },
        ),
        migrations.CreateModel(
            name='Stockdesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=1024)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dae', models.DateField()),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=5000)),
                ('translation', models.CharField(blank=True, default='', max_length=512)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist')),
            ],
            options={
                'db_table': 'currentstock',
            },
        ),
        migrations.CreateModel(
            name='UsCompanyDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('stock_date', models.DateField()),
                ('close', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('company_code', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist')),
            ],
            options={
                'ordering': ['-stock_date'],
                'unique_together': {('company_code', 'stock_date')},
            },
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('end_date', models.DateField()),
                ('revenue', models.IntegerField(default=0, null=True)),
                ('gross_profit', models.IntegerField(default=0, null=True)),
                ('operating_income', models.IntegerField(default=0, null=True)),
                ('net_income', models.IntegerField(default=0, null=True)),
                ('company_code', models.ForeignKey(db_column='symbol', default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist')),
            ],
            options={
                'db_table': 'incomestatement',
                'ordering': ['-end_date'],
                'unique_together': {('company_code', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('end_date', models.DateField()),
                ('total_liability', models.BigIntegerField(default=0, null=True)),
                ('total_stockholder_equity', models.BigIntegerField(default=0, null=True)),
                ('total_assets', models.BigIntegerField(default=0, null=True)),
                ('total_current_assets', models.BigIntegerField(default=0, null=True)),
                ('total_current_liability', models.BigIntegerField(default=0, null=True)),
                ('company_code', models.ForeignKey(db_column='symbol', default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist')),
            ],
            options={
                'db_table': 'balancesheet',
                'ordering': ['-end_date'],
                'unique_together': {('company_code', 'end_date')},
            },
        ),
    ]
