# Generated by Django 3.2.8 on 2021-11-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist')),
            ],
            options={
                'db_table': 'currentstock',
            },
        ),
    ]
