# Generated by Django 3.2.8 on 2021-10-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsCompanyDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('stock_date', models.DateField()),
                ('close', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist')),
            ],
            options={
                'ordering': ['-stock_date'],
                'unique_together': {('company_code', 'stock_date')},
            },
        ),
    ]
