# Generated by Django 3.2.8 on 2021-11-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_currentstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstock',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
