# Generated by Django 3.2.8 on 2021-10-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_newday_uscompanydaily'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newDay',
        ),
    ]
