# Generated by Django 3.2.8 on 2021-11-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_currentstock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockdesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=512)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist')),
            ],
        ),
    ]
