# Generated by Django 3.2.8 on 2021-11-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdesc',
            name='desc',
        ),
        migrations.AddField(
            model_name='stockdesc',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
