# Generated by Django 3.2.8 on 2021-11-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20211120_0347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscontents',
            options={'ordering': ['-date']},
        ),
    ]
