# Generated by Django 3.2.8 on 2021-10-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_incomestatemente'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('end_date', models.DateField()),
                ('revenue', models.IntegerField()),
                ('grossProfit', models.IntegerField()),
                ('operatingIncome', models.IntegerField()),
                ('netIncome', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='IncomeStatemente',
        ),
    ]
