# Generated by Django 3.2.8 on 2021-11-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_newscontents_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscontents',
            name='summary',
        ),
        migrations.AddField(
            model_name='newscontents',
            name='title_translation',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
