# Generated by Django 3.2.8 on 2021-10-18 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20211018_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomestatement',
            options={'ordering': ['-end_date']},
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='company_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.uscompanydaily'),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='grossProfit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='netIncome',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='operatingIncome',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='revenue',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='incomestatement',
            unique_together={('company_code', 'end_date')},
        ),
        migrations.AlterModelTable(
            name='incomestatement',
            table='incomestatement',
        ),
    ]
