# Generated by Django 3.2.8 on 2021-10-18 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20211018_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomestatement',
            options={'ordering': ['-endDate']},
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='company_code',
            new_name='companyCode',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.AlterUniqueTogether(
            name='incomestatement',
            unique_together={('companyCode', 'endDate')},
        ),
    ]
