# Generated by Django 3.2.8 on 2021-10-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20211018_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomestatement',
            options={'ordering': ['-end_date']},
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='companyCode',
            new_name='company_code',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='grossProfit',
            new_name='gross_profit',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='netIncome',
            new_name='net_income',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='operatingIncome',
            new_name='operating_income',
        ),
        migrations.AlterUniqueTogether(
            name='incomestatement',
            unique_together={('company_code', 'end_date')},
        ),
    ]
