# Generated by Django 3.2.8 on 2021-10-18 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20211018_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomestatement',
            name='company_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist'),
        ),
    ]
