# Generated by Django 3.2.8 on 2021-10-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_incomestatement_company_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('end_date', models.DateField()),
                ('total_liability', models.IntegerField(default=0, null=True)),
                ('total_stockholder_equity', models.IntegerField(default=0, null=True)),
                ('total_Assets', models.IntegerField(default=0, null=True)),
                ('total_current_assets', models.IntegerField(default=0, null=True)),
                ('total_current_liability', models.IntegerField(default=0, null=True)),
                ('company_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist')),
            ],
            options={
                'db_table': 'balancesheet',
                'ordering': ['-end_date'],
                'unique_together': {('company_code', 'end_date')},
            },
        ),
    ]
