# Generated by Django 3.2.8 on 2021-10-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_balancesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='total_Assets',
            new_name='total_assets',
        ),
    ]
