# Generated by Django 3.2.8 on 2021-11-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='portfolio',
        ),
    ]
