# Generated by Django 3.2.8 on 2021-11-26 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0006_auto_20211122_1717'),
        ('portfolio', '0002_auto_20211122_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField(default=10000.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('game_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.investgame')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist')),
            ],
        ),
    ]
