# Generated by Django 3.2.8 on 2021-11-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_gameportfolio_investgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameportfolio',
            name='game_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='portfolio.investgame'),
        ),
    ]
