# Generated by Django 3.2.8 on 2021-11-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
