# Generated by Django 3.2.8 on 2021-10-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20211018_2212'),
        ('pybo', '0003_auto_20211027_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='symbol',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist'),
        ),
        migrations.AddField(
            model_name='comment',
            name='symbol',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usstocklist'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
