# Generated by Django 3.2.8 on 2021-11-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_auto_20211102_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
