# Generated by Django 3.2.8 on 2021-11-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_blog_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pybo.blog'),
        ),
    ]
